import Head from 'next/head'
import { Inter } from 'next/font/google'
import TextArea from '@/components/playground/TextArea'
import PlaygroundMessages from '@/components/playground/PlaygroundMessages'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen">
        <div className="flex flex-row items-stretch h-full">
          <TextArea title="System" className="min-w-[300px]" placeholder="You are a helpful assistant." />
          <PlaygroundMessages />
        </div>
      </main>
    </>
  )
}
